import { Meal, ChatMessage, UserProfile } from '@/types';

export const MOCK_MEALS: Meal[] = [
  {
    id: '1',
    title: 'Avocado Toast with Eggs',
    image: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c820?w=400',
    calories: 380,
    protein: 18,
    carbs: 32,
    fat: 22,
    prepTime: 10,
    category: 'Breakfast',
    tags: ['Quick', 'High Protein', 'Vegetarian'],
    description: 'Creamy avocado on toasted sourdough topped with poached eggs and chili flakes.',
    ingredients: ['2 slices sourdough', '1 ripe avocado', '2 eggs', 'chili flakes', 'lemon juice', 'salt & pepper'],
    instructions: ['Toast bread', 'Mash avocado with lemon juice', 'Poach eggs', 'Assemble and season'],
  },
  {
    id: '2',
    title: 'Grilled Chicken Salad',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
    calories: 320,
    protein: 42,
    carbs: 12,
    fat: 10,
    prepTime: 20,
    category: 'Lunch',
    tags: ['High Protein', 'Low Carb', 'Keto'],
    description: 'Juicy grilled chicken breast over a bed of mixed greens with a light vinaigrette.',
    ingredients: ['200g chicken breast', 'mixed greens', 'cherry tomatoes', 'cucumber', 'olive oil', 'balsamic'],
    instructions: ['Season and grill chicken', 'Chop vegetables', 'Toss salad', 'Slice chicken and serve'],
  },
  {
    id: '3',
    title: 'Salmon & Quinoa Bowl',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400',
    calories: 520,
    protein: 38,
    carbs: 45,
    fat: 18,
    prepTime: 25,
    category: 'Dinner',
    tags: ['Omega-3', 'Balanced', 'Healthy'],
    description: 'Pan-seared salmon fillet over fluffy quinoa with roasted vegetables.',
    ingredients: ['180g salmon fillet', '100g quinoa', 'broccoli', 'sweet potato', 'lemon', 'olive oil'],
    instructions: ['Cook quinoa', 'Roast vegetables', 'Pan-sear salmon', 'Assemble bowl'],
  },
  {
    id: '4',
    title: 'Greek Yogurt Parfait',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400',
    calories: 280,
    protein: 20,
    carbs: 38,
    fat: 5,
    prepTime: 5,
    category: 'Snack',
    tags: ['Quick', 'Probiotic', 'Vegetarian'],
    description: 'Layered Greek yogurt with fresh berries, granola, and a drizzle of honey.',
    ingredients: ['200g Greek yogurt', 'mixed berries', '30g granola', 'honey', 'chia seeds'],
    instructions: ['Layer yogurt', 'Add berries', 'Top with granola', 'Drizzle honey'],
  },
  {
    id: '5',
    title: 'Veggie Stir Fry',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400',
    calories: 290,
    protein: 12,
    carbs: 42,
    fat: 9,
    prepTime: 15,
    category: 'Dinner',
    tags: ['Vegan', 'Quick', 'Fiber-Rich'],
    description: 'Colorful mix of vegetables stir-fried in a savory soy-ginger sauce over brown rice.',
    ingredients: ['mixed vegetables', 'brown rice', 'soy sauce', 'ginger', 'garlic', 'sesame oil'],
    instructions: ['Cook rice', 'Prep vegetables', 'Stir fry in wok', 'Add sauce and serve'],
  },
  {
    id: '6',
    title: 'Overnight Oats',
    image: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=400',
    calories: 340,
    protein: 14,
    carbs: 52,
    fat: 8,
    prepTime: 5,
    category: 'Breakfast',
    tags: ['Meal Prep', 'Fiber', 'Vegetarian'],
    description: 'Creamy overnight oats loaded with banana, peanut butter, and chocolate chips.',
    ingredients: ['80g rolled oats', '200ml almond milk', '1 banana', 'peanut butter', 'chocolate chips'],
    instructions: ['Combine oats and milk', 'Mix in toppings', 'Refrigerate overnight', 'Serve cold'],
  },
  {
    id: '7',
    title: 'Turkey Wrap',
    image: 'https://images.unsplash.com/photo-1461009683693-342af2f2d6ce?w=400',
    calories: 410,
    protein: 32,
    carbs: 38,
    fat: 14,
    prepTime: 10,
    category: 'Lunch',
    tags: ['High Protein', 'On-the-Go', 'Lean'],
    description: 'Sliced turkey breast with lettuce, tomato, and hummus in a whole wheat wrap.',
    ingredients: ['whole wheat wrap', '100g turkey breast', 'lettuce', 'tomato', 'hummus', 'cucumber'],
    instructions: ['Spread hummus on wrap', 'Layer turkey and vegetables', 'Roll tightly', 'Slice in half'],
  },
  {
    id: '8',
    title: 'Protein Smoothie Bowl',
    image: 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=400',
    calories: 360,
    protein: 28,
    carbs: 44,
    fat: 7,
    prepTime: 8,
    category: 'Breakfast',
    tags: ['High Protein', 'Post-Workout', 'Vegan'],
    description: 'Thick blended smoothie bowl with protein powder, topped with seeds and fresh fruit.',
    ingredients: ['protein powder', 'frozen banana', 'almond milk', 'spinach', 'mixed seeds', 'berries'],
    instructions: ['Blend until thick', 'Pour into bowl', 'Add toppings', 'Serve immediately'],
  },
];

export const MOCK_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: '1',
    text: 'Hello! I\'m your AI nutrition assistant. How can I help you reach your health goals today?',
    sender: 'ai',
    timestamp: new Date(Date.now() - 60000 * 5),
  },
  {
    id: '2',
    text: 'Can you suggest a high-protein dinner under 500 calories?',
    sender: 'user',
    timestamp: new Date(Date.now() - 60000 * 4),
  },
  {
    id: '3',
    text: 'Great choice! I\'d recommend the Salmon & Quinoa Bowl — it has 38g of protein and only 520 calories. It\'s packed with omega-3s and keeps you full for hours. Want me to add it to your meal plan?',
    sender: 'ai',
    timestamp: new Date(Date.now() - 60000 * 3),
  },
];

export const MOCK_USER: UserProfile = {
  name: 'Alex Johnson',
  email: 'alex@example.com',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200',
  goal: 'lose_weight',
  dailyCalorieTarget: 1800,
  dietType: 'None',
  allergies: ['Peanuts'],
};
